version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest  # Use your custom image
    container_name: gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
